### ISSUE TITLE
key conflict with eng-england

### ISSUE THREAD

**Issue by slaponicus** [openfootball/ru-russia#5]
Arsenal FC from eng-england and Arsenal Tula from ru-russia both have the key "arsenal". Would it hurt to make a pull request and change it to something like "arsenaltula"?

Also the titles of the teams could be more descriptive - for example, Dynamo Moscow is just "Dynamo" which could in the future conflict with teams like Dynamo Stavropol if they are added. I'd like to change the team names to one of the more descriptive aliases if it's okay - just wanted to check before making the request and doing the work.

**Comment by geraldb** [comment]
@slaponicus  Good point. Of course. You're more than welcome. I changed the entry:

    arsenal,Arsenal|Arsenal Tula,city:Tula

to

   arsenaltula,Arsenal Tula|Arsenal,city:Tula

as an example. Note: The first name/title after the all lowercase key e.g. Arsenal Tula is the name that gets picked, that is, just move a "longer" name up-front e.g. "Dynamo Moscow" instead of just "Dynamo". Keep it up. Cheers.
PS: Still needs to update / sync the key in the league seasons.

**Comment by slaponicus** [comment]
Thanks Gerald! I rebuilt the database with the new data and now Arsenal FC doesn't get overwritten. 

Next time I see a conflict or inconsistency like this I'll go ahead and fix it myself and then make a pull request so that you don't have to do all the work. I'll also try and update the key in the league seasons soon.

Thanks for all the work you do in maintaining openfootball!
